<?php
/* 
	This controller extends the base controller (alway our creation..)
	the base controller lets us use smarty as a templating language...
	This controller allows us to automatically handle the creations of 
	autogenerated controllers based on the contents of a Mysql database..

*/
class Orm_Controller extends Controller {


	public $restful = true;

	


}
