<?php
//Generated by buildORM from the cred:Carriers

	namespace nod\orm; //so this file should live under models/nod/orm

	class CarrierBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Carriers';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function ProviderCarrier_bunch()
        {
                return $this->has_many('ProviderCarrier',Carrier_id);
               // return $this->has_one('ProviderCarrier',Carrier_id);
        }


	}//the end of class Carrier		
?>