<?php
//Generated by buildORM from the cred:EducationInstitutions

	namespace nod\orm; //so this file should live under models/nod/orm

	class EducationInstitutionBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'EducationInstitutions';
 

        //autogenerated this function... 
        public function Address()
        {
                return $this->belongs_to('Address','Address_id');
        }


        //autogenerated this function... 
        public function Phone()
        {
                return $this->belongs_to('Phone','Phone_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function ProviderEducation_bunch()
        {
                return $this->has_many('ProviderEducation',EducationInstitution_id);
               // return $this->has_one('ProviderEducation',EducationInstitution_id);
        }


	}//the end of class EducationInstitution		
?>