<?php
//Generated by buildORM from the cred:EducationLevels

	namespace nod\orm; //so this file should live under models/nod/orm

	class EducationLevelBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'EducationLevels';
 

	}//the end of class EducationLevel		
?>