<?php
//Generated by buildORM from the cred:laravel_migrations

	namespace nod\orm; //so this file should live under models/nod/orm

	class laravel_migrationBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'laravel_migrations';
 

	}//the end of class laravel_migration		
?>