<?php
//Generated by buildORM from the cred:Notes

	namespace nod\orm; //so this file should live under models/nod/orm

	class NoteBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Notes';
 

        //autogenerated this function... 
        public function row()
        {
                return $this->belongs_to('row','row_id');
        }


        //autogenerated this function... 
        public function User()
        {
                return $this->belongs_to('User','User_id');
        }


	}//the end of class Note		
?>