<?php
//Generated by buildORM from the cred:ProvidersProviderSpecialitys

	namespace nod\orm; //so this file should live under models/nod/orm

	class ProvidersProviderSpecialityBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'ProvidersProviderSpecialitys';
 

        //autogenerated this function... 
        public function ProviderSpeciality()
        {
                return $this->belongs_to('ProviderSpeciality','ProviderSpeciality_id');
        }


        //autogenerated this function... 
        public function Provider()
        {
                return $this->belongs_to('Provider','Provider_id');
        }


	}//the end of class ProvidersProviderSpeciality		
?>