<?php
//Generated by buildORM from the cred:rows

	namespace nod\orm; //so this file should live under models/nod/orm

	class rowBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'rows';
 

        //autogenerated this function... 
        public function Note_bunch()
        {
                return $this->has_many('Note',row_id);
               // return $this->has_one('Note',row_id);
        }


        //autogenerated this function... 
        public function TagLink_bunch()
        {
                return $this->has_many('TagLink',row_id);
               // return $this->has_one('TagLink',row_id);
        }


	}//the end of class row		
?>