<?php
//Generated by buildORM from the cred:Specialitys

	namespace nod\orm; //so this file should live under models/nod/orm

	class SpecialityBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Specialitys';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function ProviderSpeciality_bunch()
        {
                return $this->has_many('ProviderSpeciality',Speciality_id);
               // return $this->has_one('ProviderSpeciality',Speciality_id);
        }


	}//the end of class Speciality		
?>