<?php
//Generated by buildORM from the cred:Tags

	namespace nod\orm; //so this file should live under models/nod/orm

	class TagBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Tags';
 

        //autogenerated this function... 
        public function TagLink_bunch()
        {
                return $this->has_many('TagLink',Tag_id);
               // return $this->has_one('TagLink',Tag_id);
        }


	}//the end of class Tag		
?>