<?php
//Generated by buildORM from the cred:taxonomys

	namespace nod\orm; //so this file should live under models/nod/orm

	class taxonomyBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'taxonomys';
 

	}//the end of class taxonomy		
?>