<?php
//Generated by buildORM from the cred:Tests

	namespace nod\orm; //so this file should live under models/nod/orm

	class TestBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Tests';
 

	}//the end of class Test		
?>