<?php
//Generated by buildORM from the cred:users

	namespace nod\orm; //so this file should live under models/nod/orm

	class userBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'users';
 

	}//the end of class user		
?>