<?php
//Generated by buildORM from the ourlaravel:Addresss

	class Address_base extends Eloquent{

		public static $table = 'Addresss';
 

        //autogenerated this function... 
        public function State()
        {
                return $this->belongs_to('State','State_id');
        }


        //autogenerated this function... 
        public function County()
        {
                return $this->belongs_to('County','County_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


	}//the end of class Address		
?>