<?php
//Generated by buildORM from the cred:Addresss

	

	class AddressBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Addresss';
 

        //autogenerated this function... 
        public function State()
        {
                return $this->belongs_to('State','state_id');
        }


        //autogenerated this function... 
        public function County()
        {
                return $this->belongs_to('County','county_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Board_bunch()
        {
                return $this->has_many('Board',address_id);
               // return $this->has_one('Board',address_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_bunch()
        {
                return $this->has_many('EducationInstitution',address_id);
               // return $this->has_one('EducationInstitution',address_id);
        }


        //autogenerated this function... 
        public function FormTest_bunch()
        {
                return $this->has_many('FormTest',address_id);
               // return $this->has_one('FormTest',address_id);
        }


        //autogenerated this function... 
        public function Provider_from_Birth_bunch()
        {
                return $this->has_many('Provider',birth_provider_id);
               // return $this->has_one('Provider',birth_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Home_bunch()
        {
                return $this->has_many('Provider',home_provider_id);
               // return $this->has_one('Provider',home_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_bunch()
        {
                return $this->has_many('Provider',corr_provider_id);
               // return $this->has_one('Provider',corr_provider_id);
        }


	}//the end of class Address		
?>