<?php
//Generated by buildORM from the cred:Addresss

	class AddressBase extends Eloquent{

		public static $table = 'Addresss';
 

        //autogenerated this function... 
        public function State()
        {
                return $this->belongs_to('State','State_id');
        }


        //autogenerated this function... 
        public function County()
        {
                return $this->belongs_to('County','County_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function Board_bunch()
        {
                return $this->has_many('Board',Address_id);
               // return $this->has_one('Board',Address_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_bunch()
        {
                return $this->has_many('EducationInstitution',Address_id);
               // return $this->has_one('EducationInstitution',Address_id);
        }


        //autogenerated this function... 
        public function Provider_from_Birth_bunch()
        {
                return $this->has_many('Provider',Birth_Provider_id);
               // return $this->has_one('Provider',Birth_Provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Home_bunch()
        {
                return $this->has_many('Provider',Home_Provider_id);
               // return $this->has_one('Provider',Home_Provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_bunch()
        {
                return $this->has_many('Provider',Corr_Provider_id);
               // return $this->has_one('Provider',Corr_Provider_id);
        }


	}//the end of class Address		
?>