<?php
//Generated by buildORM from the cred:Countys

	

	class CountyBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Countys';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Address_bunch()
        {
                return $this->has_many('Address',county_id);
               // return $this->has_one('Address',county_id);
        }


	}//the end of class County		
?>