<?php
//Generated by buildORM from the cred:CredentialOrganizations

	class CredentialOrganizationBase extends Eloquent{

		public static $table = 'CredentialOrganizations';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function ProviderCredential_bunch()
        {
                return $this->has_many('ProviderCredential',CredentialOrganization_id);
               // return $this->has_one('ProviderCredential',CredentialOrganization_id);
        }


	}//the end of class CredentialOrganization		
?>