<?php
//Generated by buildORM from the cred:EducationInstitutions

	

	class EducationInstitutionBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'EducationInstitutions';
 

        //autogenerated this function... 
        public function Address()
        {
                return $this->belongs_to('Address','address_id');
        }


        //autogenerated this function... 
        public function Phone()
        {
                return $this->belongs_to('Phone','phone_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function ProviderEducation_bunch()
        {
                return $this->has_many('ProviderEducation',educationinstitution_id);
               // return $this->has_one('ProviderEducation',educationinstitution_id);
        }


	}//the end of class EducationInstitution		
?>