<?php
//Generated by buildORM from the ourlaravel:EducationLevels

	class EducationLevel_base extends Eloquent{

		public static $table = 'EducationLevels';
 

	}//the end of class EducationLevel		
?>