<?php
//Generated by buildORM from the ourlaravel:EducationInstitutions

	class EducationInstitution_base extends Eloquent{

		public static $table = 'EducationInstitutions';
 

        //autogenerated this function... 
        public function Address()
        {
                return $this->belongs_to('Address','Address_id');
        }


        //autogenerated this function... 
        public function Phone()
        {
                return $this->belongs_to('Phone','Phone_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


	}//the end of class EducationInstitution		
?>