<?php
//Generated by buildORM from the cred:FormTest

	

	class FormTestBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'FormTest';
 

        //autogenerated this function... 
        public function Address()
        {
                return $this->belongs_to('Address','address_id');
        }


	}//the end of class FormTest		
?>