<?php
//Generated by buildORM from the ourlaravel:laravel_migrations

	class laravel_migration_base extends Eloquent{

		public static $table = 'laravel_migrations';
 

	}//the end of class laravel_migration		
?>