<?php
//Generated by buildORM from the cred:Networks

	

	class NetworkBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Networks';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function ProviderNetwork_bunch()
        {
                return $this->has_many('ProviderNetwork',network_id);
               // return $this->has_one('ProviderNetwork',network_id);
        }


	}//the end of class Network		
?>