<?php
//Generated by buildORM from the cred:Notes

	class NoteBase extends Eloquent{

		public static $table = 'Notes';
 

        //autogenerated this function... 
        public function row()
        {
                return $this->belongs_to('row','row_id');
        }


        //autogenerated this function... 
        public function User()
        {
                return $this->belongs_to('User','User_id');
        }


	}//the end of class Note		
?>