<?php
//Generated by buildORM from the ourlaravel:Notes

	class Note_base extends Eloquent{

		public static $table = 'Notes';
 

        //autogenerated this function... 
        public function row()
        {
                return $this->belongs_to('Row','row_id');
        }


        //autogenerated this function... 
        public function User()
        {
                return $this->belongs_to('User','User_id');
        }


	}//the end of class Note		
?>