<?php
//Generated by buildORM from the cred:Phones

	

	class PhoneBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Phones';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function Board_bunch()
        {
                return $this->has_many('Board',phone_id);
               // return $this->has_one('Board',phone_id);
        }


        //autogenerated this function... 
        public function Board_from_Fax_bunch()
        {
                return $this->has_many('Board',fax_board_id);
               // return $this->has_one('Board',fax_board_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_bunch()
        {
                return $this->has_many('EducationInstitution',phone_id);
               // return $this->has_one('EducationInstitution',phone_id);
        }


        //autogenerated this function... 
        public function Provider_from_Home_bunch()
        {
                return $this->has_many('Provider',home_provider_id);
               // return $this->has_one('Provider',home_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_bunch()
        {
                return $this->has_many('Provider',corr_provider_id);
               // return $this->has_one('Provider',corr_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_Fax_bunch()
        {
                return $this->has_many('Provider',corr_fax_provider_id);
               // return $this->has_one('Provider',corr_fax_provider_id);
        }


	}//the end of class Phone		
?>