<?php
//Generated by buildORM from the ourlaravel:Phones

	class Phone_base extends Eloquent{

		public static $table = 'Phones';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function Board_bunch()
        {
                return $this->has_many('Board',Phone_id);
               // return $this->has_one('Board',Phone_id);
        }


        //autogenerated this function... 
        public function Board_bunch()
        {
                return $this->has_many('Board',Fax_Phone_id);
               // return $this->has_one('Board',Fax_Phone_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_bunch()
        {
                return $this->has_many('EducationInstitution',Phone_id);
               // return $this->has_one('EducationInstitution',Phone_id);
        }


	}//the end of class Phone		
?>