<?php
//Generated by buildORM from the cred:Phones

	class PhoneBase extends Eloquent{

		public static $table = 'Phones';
 

        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function Board_bunch()
        {
                return $this->has_many('Board',Phone_id);
               // return $this->has_one('Board',Phone_id);
        }


        //autogenerated this function... 
        public function Board_from_Fax_bunch()
        {
                return $this->has_many('Board',Fax_Board_id);
               // return $this->has_one('Board',Fax_Board_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_bunch()
        {
                return $this->has_many('EducationInstitution',Phone_id);
               // return $this->has_one('EducationInstitution',Phone_id);
        }


        //autogenerated this function... 
        public function Provider_from_Home_bunch()
        {
                return $this->has_many('Provider',Home_Provider_id);
               // return $this->has_one('Provider',Home_Provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_bunch()
        {
                return $this->has_many('Provider',Corr_Provider_id);
               // return $this->has_one('Provider',Corr_Provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_Corr_Fax_bunch()
        {
                return $this->has_many('Provider',Corr_Fax_Provider_id);
               // return $this->has_one('Provider',Corr_Fax_Provider_id);
        }


	}//the end of class Phone		
?>