<?php
//Generated by buildORM from the cred:ProviderEducations

	

	class ProviderEducationBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'ProviderEducations';
 

        //autogenerated this function... 
        public function Provider()
        {
                return $this->belongs_to('Provider','provider_id');
        }


        //autogenerated this function... 
        public function ProviderSpeciality()
        {
                return $this->belongs_to('ProviderSpeciality','providerspeciality_id');
        }


        //autogenerated this function... 
        public function EducationInstitution()
        {
                return $this->belongs_to('EducationInstitution','educationinstitution_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_user_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_user_id');
        }


        //autogenerated this function... 
        public function ProviderEducationsProviderEducation_bunch()
        {
                return $this->has_many('ProviderEducationsProviderEducation',providereducation_id);
               // return $this->has_one('ProviderEducationsProviderEducation',providereducation_id);
        }


	}//the end of class ProviderEducation		
?>