<?php
//Generated by buildORM from the cred:ProviderEducationsProviderEducations

	class ProviderEducationsProviderEducationBase extends Eloquent{

		public static $table = 'ProviderEducationsProviderEducations';
 

        //autogenerated this function... 
        public function ProviderEducation()
        {
                return $this->belongs_to('ProviderEducation','ProviderEducation_id');
        }


	}//the end of class ProviderEducationsProviderEducation		
?>