<?php
//Generated by buildORM from the ourlaravel:ProviderSpecialitys

	class ProviderSpeciality_base extends Eloquent{

		public static $table = 'ProviderSpecialitys';
 

        //autogenerated this function... 
        public function Provider()
        {
                return $this->belongs_to('Provider','Provider_id');
        }


        //autogenerated this function... 
        public function Speciality()
        {
                return $this->belongs_to('Speciality','Speciality_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function Board()
        {
                return $this->belongs_to('Board','Board_id');
        }


        //autogenerated this function... 
        public function ProviderEducation_bunch()
        {
                return $this->has_many('ProviderEducation',ProviderSpeciality_id);
               // return $this->has_one('ProviderEducation',ProviderSpeciality_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_bunch()
        {
                return $this->has_many('ProviderLicense',ProviderSpeciality_id);
               // return $this->has_one('ProviderLicense',ProviderSpeciality_id);
        }


	}//the end of class ProviderSpeciality		
?>