<?php
//Generated by buildORM from the cred:ProviderEducations

	class ProviderEducationBase extends Eloquent{

		public static $table = 'ProviderEducations';
 

        //autogenerated this function... 
        public function Provider()
        {
                return $this->belongs_to('Provider','Provider_id');
        }


        //autogenerated this function... 
        public function ProviderSpeciality()
        {
                return $this->belongs_to('ProviderSpeciality','ProviderSpeciality_id');
        }


        //autogenerated this function... 
        public function EducationInstitution()
        {
                return $this->belongs_to('EducationInstitution','EducationInstitution_id');
        }


        //autogenerated this function... 
        public function created_by_User()
        {
                return $this->belongs_to('User','created_by_User_id');
        }


        //autogenerated this function... 
        public function modified_by_User()
        {
                return $this->belongs_to('User','modified_by_User_id');
        }


        //autogenerated this function... 
        public function ProviderEducationsProviderEducation_bunch()
        {
                return $this->has_many('ProviderEducationsProviderEducation',ProviderEducation_id);
               // return $this->has_one('ProviderEducationsProviderEducation',ProviderEducation_id);
        }


	}//the end of class ProviderEducation		
?>