<?php
//Generated by buildORM from the cred:States

	

	class StateBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'States';
 

        //autogenerated this function... 
        public function Address_bunch()
        {
                return $this->has_many('Address',state_id);
               // return $this->has_one('Address',state_id);
        }


        //autogenerated this function... 
        public function ProviderCoverage_bunch()
        {
                return $this->has_many('ProviderCoverage',state_id);
               // return $this->has_one('ProviderCoverage',state_id);
        }


        //autogenerated this function... 
        public function ProviderHospital_bunch()
        {
                return $this->has_many('ProviderHospital',state_id);
               // return $this->has_one('ProviderHospital',state_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_bunch()
        {
                return $this->has_many('ProviderLicense',state_id);
               // return $this->has_one('ProviderLicense',state_id);
        }


	}//the end of class State		
?>