<?php
//Generated by buildORM from the cred:TagLinks

	

	class TagLinkBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'TagLinks';
 

        //autogenerated this function... 
        public function row()
        {
                return $this->belongs_to('row','row_id');
        }


        //autogenerated this function... 
        public function Tag()
        {
                return $this->belongs_to('Tag','tag_id');
        }


        //autogenerated this function... 
        public function User()
        {
                return $this->belongs_to('User','user_id');
        }


	}//the end of class TagLink		
?>