<?php
//Generated by buildORM from the cred:Users

	

	class UserBase extends BaseORM{ //which extends Eloquent...

		public static $table = 'Users';
 

        //autogenerated this function... 
        public function Address_from_created_by_bunch()
        {
                return $this->has_many('Address',created_by_address_id);
               // return $this->has_one('Address',created_by_address_id);
        }


        //autogenerated this function... 
        public function Address_from_modified_by_bunch()
        {
                return $this->has_many('Address',modified_by_address_id);
               // return $this->has_one('Address',modified_by_address_id);
        }


        //autogenerated this function... 
        public function Board_from_created_by_bunch()
        {
                return $this->has_many('Board',created_by_board_id);
               // return $this->has_one('Board',created_by_board_id);
        }


        //autogenerated this function... 
        public function Board_from_modified_by_bunch()
        {
                return $this->has_many('Board',modified_by_board_id);
               // return $this->has_one('Board',modified_by_board_id);
        }


        //autogenerated this function... 
        public function Carrier_from_created_by_bunch()
        {
                return $this->has_many('Carrier',created_by_carrier_id);
               // return $this->has_one('Carrier',created_by_carrier_id);
        }


        //autogenerated this function... 
        public function Carrier_from_modified_by_bunch()
        {
                return $this->has_many('Carrier',modified_by_carrier_id);
               // return $this->has_one('Carrier',modified_by_carrier_id);
        }


        //autogenerated this function... 
        public function County_from_created_by_bunch()
        {
                return $this->has_many('County',created_by_county_id);
               // return $this->has_one('County',created_by_county_id);
        }


        //autogenerated this function... 
        public function County_from_modified_by_bunch()
        {
                return $this->has_many('County',modified_by_county_id);
               // return $this->has_one('County',modified_by_county_id);
        }


        //autogenerated this function... 
        public function CredentialOrganization_from_created_by_bunch()
        {
                return $this->has_many('CredentialOrganization',created_by_credentialorganization_id);
               // return $this->has_one('CredentialOrganization',created_by_credentialorganization_id);
        }


        //autogenerated this function... 
        public function CredentialOrganization_from_modified_by_bunch()
        {
                return $this->has_many('CredentialOrganization',modified_by_credentialorganization_id);
               // return $this->has_one('CredentialOrganization',modified_by_credentialorganization_id);
        }


        //autogenerated this function... 
        public function DocumentType_from_created_by_bunch()
        {
                return $this->has_many('DocumentType',created_by_documenttype_id);
               // return $this->has_one('DocumentType',created_by_documenttype_id);
        }


        //autogenerated this function... 
        public function DocumentType_from_modified_by_bunch()
        {
                return $this->has_many('DocumentType',modified_by_documenttype_id);
               // return $this->has_one('DocumentType',modified_by_documenttype_id);
        }


        //autogenerated this function... 
        public function Document_from_created_by_bunch()
        {
                return $this->has_many('Document',created_by_document_id);
               // return $this->has_one('Document',created_by_document_id);
        }


        //autogenerated this function... 
        public function Document_from_modified_by_bunch()
        {
                return $this->has_many('Document',modified_by_document_id);
               // return $this->has_one('Document',modified_by_document_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_from_created_by_bunch()
        {
                return $this->has_many('EducationInstitution',created_by_educationinstitution_id);
               // return $this->has_one('EducationInstitution',created_by_educationinstitution_id);
        }


        //autogenerated this function... 
        public function EducationInstitution_from_modified_by_bunch()
        {
                return $this->has_many('EducationInstitution',modified_by_educationinstitution_id);
               // return $this->has_one('EducationInstitution',modified_by_educationinstitution_id);
        }


        //autogenerated this function... 
        public function Gender_from_created_by_bunch()
        {
                return $this->has_many('Gender',created_by_gender_id);
               // return $this->has_one('Gender',created_by_gender_id);
        }


        //autogenerated this function... 
        public function Gender_from_modified_by_bunch()
        {
                return $this->has_many('Gender',modified_by_gender_id);
               // return $this->has_one('Gender',modified_by_gender_id);
        }


        //autogenerated this function... 
        public function Network_from_created_by_bunch()
        {
                return $this->has_many('Network',created_by_network_id);
               // return $this->has_one('Network',created_by_network_id);
        }


        //autogenerated this function... 
        public function Network_from_modified_by_bunch()
        {
                return $this->has_many('Network',modified_by_network_id);
               // return $this->has_one('Network',modified_by_network_id);
        }


        //autogenerated this function... 
        public function Note_bunch()
        {
                return $this->has_many('Note',user_id);
               // return $this->has_one('Note',user_id);
        }


        //autogenerated this function... 
        public function Phone_from_created_by_bunch()
        {
                return $this->has_many('Phone',created_by_phone_id);
               // return $this->has_one('Phone',created_by_phone_id);
        }


        //autogenerated this function... 
        public function Phone_from_modified_by_bunch()
        {
                return $this->has_many('Phone',modified_by_phone_id);
               // return $this->has_one('Phone',modified_by_phone_id);
        }


        //autogenerated this function... 
        public function ProviderCarrier_from_created_by_bunch()
        {
                return $this->has_many('ProviderCarrier',created_by_providercarrier_id);
               // return $this->has_one('ProviderCarrier',created_by_providercarrier_id);
        }


        //autogenerated this function... 
        public function ProviderCarrier_from_modified_by_bunch()
        {
                return $this->has_many('ProviderCarrier',modified_by_providercarrier_id);
               // return $this->has_one('ProviderCarrier',modified_by_providercarrier_id);
        }


        //autogenerated this function... 
        public function ProviderCoverage_from_created_by_bunch()
        {
                return $this->has_many('ProviderCoverage',created_by_providercoverage_id);
               // return $this->has_one('ProviderCoverage',created_by_providercoverage_id);
        }


        //autogenerated this function... 
        public function ProviderCoverage_from_modified_by_bunch()
        {
                return $this->has_many('ProviderCoverage',modified_by_providercoverage_id);
               // return $this->has_one('ProviderCoverage',modified_by_providercoverage_id);
        }


        //autogenerated this function... 
        public function ProviderCredential_from_created_by_bunch()
        {
                return $this->has_many('ProviderCredential',created_by_providercredential_id);
               // return $this->has_one('ProviderCredential',created_by_providercredential_id);
        }


        //autogenerated this function... 
        public function ProviderCredential_from_modified_by_bunch()
        {
                return $this->has_many('ProviderCredential',modified_by_providercredential_id);
               // return $this->has_one('ProviderCredential',modified_by_providercredential_id);
        }


        //autogenerated this function... 
        public function ProviderEducation_from_created_by_bunch()
        {
                return $this->has_many('ProviderEducation',created_by_providereducation_id);
               // return $this->has_one('ProviderEducation',created_by_providereducation_id);
        }


        //autogenerated this function... 
        public function ProviderEducation_from_modified_by_bunch()
        {
                return $this->has_many('ProviderEducation',modified_by_providereducation_id);
               // return $this->has_one('ProviderEducation',modified_by_providereducation_id);
        }


        //autogenerated this function... 
        public function ProviderHospital_from_created_by_bunch()
        {
                return $this->has_many('ProviderHospital',created_by_providerhospital_id);
               // return $this->has_one('ProviderHospital',created_by_providerhospital_id);
        }


        //autogenerated this function... 
        public function ProviderHospital_from_modified_by_bunch()
        {
                return $this->has_many('ProviderHospital',modified_by_providerhospital_id);
               // return $this->has_one('ProviderHospital',modified_by_providerhospital_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_from_created_by_bunch()
        {
                return $this->has_many('ProviderLicense',created_by_providerlicense_id);
               // return $this->has_one('ProviderLicense',created_by_providerlicense_id);
        }


        //autogenerated this function... 
        public function ProviderLicense_from_modified_by_bunch()
        {
                return $this->has_many('ProviderLicense',modified_by_providerlicense_id);
               // return $this->has_one('ProviderLicense',modified_by_providerlicense_id);
        }


        //autogenerated this function... 
        public function ProviderNetwork_from_created_by_bunch()
        {
                return $this->has_many('ProviderNetwork',created_by_providernetwork_id);
               // return $this->has_one('ProviderNetwork',created_by_providernetwork_id);
        }


        //autogenerated this function... 
        public function ProviderNetwork_from_modified_by_bunch()
        {
                return $this->has_many('ProviderNetwork',modified_by_providernetwork_id);
               // return $this->has_one('ProviderNetwork',modified_by_providernetwork_id);
        }


        //autogenerated this function... 
        public function ProviderReference_from_created_by_bunch()
        {
                return $this->has_many('ProviderReference',created_by_providerreference_id);
               // return $this->has_one('ProviderReference',created_by_providerreference_id);
        }


        //autogenerated this function... 
        public function ProviderReference_from_modified_by_bunch()
        {
                return $this->has_many('ProviderReference',modified_by_providerreference_id);
               // return $this->has_one('ProviderReference',modified_by_providerreference_id);
        }


        //autogenerated this function... 
        public function ProviderSpeciality_from_created_by_bunch()
        {
                return $this->has_many('ProviderSpeciality',created_by_providerspeciality_id);
               // return $this->has_one('ProviderSpeciality',created_by_providerspeciality_id);
        }


        //autogenerated this function... 
        public function ProviderSpeciality_from_modified_by_bunch()
        {
                return $this->has_many('ProviderSpeciality',modified_by_providerspeciality_id);
               // return $this->has_one('ProviderSpeciality',modified_by_providerspeciality_id);
        }


        //autogenerated this function... 
        public function ProviderStatus_from_created_by_bunch()
        {
                return $this->has_many('ProviderStatus',created_by_providerstatus_id);
               // return $this->has_one('ProviderStatus',created_by_providerstatus_id);
        }


        //autogenerated this function... 
        public function ProviderStatus_from_modified_by_bunch()
        {
                return $this->has_many('ProviderStatus',modified_by_providerstatus_id);
               // return $this->has_one('ProviderStatus',modified_by_providerstatus_id);
        }


        //autogenerated this function... 
        public function Provider_from_created_by_bunch()
        {
                return $this->has_many('Provider',created_by_provider_id);
               // return $this->has_one('Provider',created_by_provider_id);
        }


        //autogenerated this function... 
        public function Provider_from_modified_by_bunch()
        {
                return $this->has_many('Provider',modified_by_provider_id);
               // return $this->has_one('Provider',modified_by_provider_id);
        }


        //autogenerated this function... 
        public function Speciality_from_created_by_bunch()
        {
                return $this->has_many('Speciality',created_by_speciality_id);
               // return $this->has_one('Speciality',created_by_speciality_id);
        }


        //autogenerated this function... 
        public function Speciality_from_modified_by_bunch()
        {
                return $this->has_many('Speciality',modified_by_speciality_id);
               // return $this->has_one('Speciality',modified_by_speciality_id);
        }


        //autogenerated this function... 
        public function TagLink_bunch()
        {
                return $this->has_many('TagLink',user_id);
               // return $this->has_one('TagLink',user_id);
        }


	}//the end of class User		
?>